name: Deploy GitHub Pages

on:
  push:
    branches:
      - "*"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --user pipenv
      - run: pipenv install
      - uses: jakebailey/pyright-action@v1
