name: Test

on:
  push:
    branches:
      - "*"

env:
  PYTHON_VERSION: 3.9.9

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install dependencies
        run: pip3 install -r requirements.txt

      - name: test
        run: make test_ci
